DROP DATABASE IF EXISTS recipe_db;
CREATE DATABASE recipe_db;
USE recipe_db;

CREATE TABLE recipe (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  num_of_servings INT UNSIGNED,
  cook_time INT UNSIGNED,
  directions TEXT,
  is_publish BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 특정 db전용 계정 생성
DROP USER 'food'@'%';
CREATE USER 'food'@'%' IDENTIFIED BY '2052';
GRANT ALL PRIVILEGES ON recipe_db.* TO 'food'@'%';

insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (1, 'Pettyfer', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 976, 242, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', true, '2012-05-01 19:55:59', '2010-03-05 02:31:10');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (2, 'Dyet', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 477, 956, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', true, '2009-03-06 10:29:46', '2019-02-16 22:55:40');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (3, 'Meader', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 651, 647, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', true, '2013-05-17 11:48:49', '2006-12-10 04:29:12');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (4, 'Osgorby', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 808, 108, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', false, '2005-02-15 20:32:23', '2010-08-27 07:51:02');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (5, 'Goodbanne', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 28, 363, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', false, '2000-02-22 18:57:19', '2011-10-30 20:01:12');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (6, 'Spilsted', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 814, 875, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', false, '2019-12-12 19:08:02', '2011-01-04 06:27:01');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (7, 'True', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 489, 0, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', false, '2004-01-06 10:14:20', '2020-02-21 07:24:07');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (8, 'Osmond', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 328, 997, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', true, '2013-01-13 04:10:06', '2009-08-06 01:35:40');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (9, 'Bawden', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 717, 986, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', true, '2008-05-14 10:38:52', '2011-05-19 22:51:54');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (10, 'Ambroziak', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 151, 803, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', true, '2002-03-16 17:47:43', '2005-02-26 21:51:51');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (11, 'Donaher', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 255, 172, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', false, '2004-11-26 22:05:19', '2015-11-14 06:49:29');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (12, 'Hynson', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 285, 318, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', false, '2017-01-23 10:42:15', '2010-04-10 05:22:50');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (13, 'Ralph', 'Fusce consequat. Nulla nisl. Nunc nisl.', 693, 329, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', true, '2000-04-03 17:28:11', '2002-07-29 20:21:08');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (14, 'Mattosoff', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 72, 816, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', false, '2004-02-15 18:46:30', '2006-05-30 23:54:08');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (15, 'Kenny', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 519, 274, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', false, '2019-01-07 07:24:15', '2006-09-09 17:23:11');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (16, 'Gwyn', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 877, 188, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', false, '2015-07-25 18:19:13', '2006-02-08 05:11:52');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (17, 'Dyzart', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 352, 644, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', false, '2006-01-17 18:44:09', '2019-06-17 04:52:45');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (18, 'Cadigan', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 724, 110, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', true, '2018-01-31 15:09:41', '2008-04-04 00:40:22');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (19, 'Lancley', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 529, 554, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', true, '2012-06-14 00:11:32', '2021-07-08 19:40:36');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (20, 'Knagges', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 353, 604, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', true, '2014-06-27 18:38:50', '2001-01-31 14:59:57');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (21, 'Spilsbury', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 927, 682, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', true, '2019-06-27 10:57:54', '2000-12-08 17:47:26');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (22, 'Younge', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 375, 895, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', true, '2006-11-14 12:42:59', '2005-09-11 03:11:26');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (23, 'Cino', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 249, 800, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', true, '2022-09-07 16:46:05', '2016-10-27 17:05:26');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (24, 'Buckston', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 267, 908, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', true, '2012-01-20 22:43:17', '2000-12-15 10:01:45');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (25, 'Murby', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 520, 462, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', false, '2005-02-19 22:18:50', '2015-12-10 14:20:10');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (26, 'Mander', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 803, 182, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', true, '2019-10-30 11:37:49', '2004-04-20 09:39:41');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (27, 'Petriello', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 736, 373, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', true, '2018-12-31 07:59:09', '2012-08-23 16:09:29');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (28, 'Kabisch', 'Fusce consequat. Nulla nisl. Nunc nisl.', 313, 40, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', false, '2002-08-10 13:21:21', '2020-05-26 16:31:04');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (29, 'Schonfelder', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 86, 984, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', false, '2000-04-19 02:04:24', '2020-03-05 09:38:04');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (30, 'Gai', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 377, 291, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', true, '2004-09-29 01:32:12', '2011-01-07 07:19:48');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (31, 'MacGall', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 935, 861, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', true, '2008-01-18 17:34:53', '2014-08-21 07:52:20');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (32, 'Le Floch', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 728, 674, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', false, '2012-09-02 16:34:46', '2022-08-21 05:48:30');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (33, 'Cron', 'Fusce consequat. Nulla nisl. Nunc nisl.', 226, 962, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', false, '2020-09-20 08:11:43', '2017-12-22 09:00:55');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (34, 'Routhorn', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 557, 737, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', false, '2009-03-10 03:40:25', '2014-04-29 17:33:34');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (35, 'Phettiplace', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 964, 781, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', true, '2022-10-25 19:40:51', '2002-06-11 00:09:36');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (36, 'Martinson', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 553, 647, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', false, '2006-03-07 17:34:21', '2019-09-08 16:47:13');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (37, 'Bennetto', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 36, 141, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', false, '2009-03-18 23:21:55', '2013-04-07 23:01:32');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (38, 'Carlone', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 751, 590, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', false, '2009-05-21 02:19:36', '2017-07-30 15:55:35');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (39, 'Dockray', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 846, 881, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', false, '2017-11-14 10:58:59', '2003-04-21 08:00:45');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (40, 'Sowrey', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 945, 329, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', true, '2000-05-18 08:58:27', '2006-09-27 20:26:24');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (41, 'Coppock.', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 23, 763, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', false, '2009-03-28 23:25:05', '2016-12-12 04:46:31');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (42, 'Colegrove', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 218, 974, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', false, '2001-04-26 09:52:37', '2012-07-23 11:59:04');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (43, 'Butcher', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 627, 108, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', true, '2012-11-14 13:19:08', '2018-03-24 13:34:27');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (44, 'L''Episcopio', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 491, 847, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', true, '2015-11-04 10:58:53', '2009-05-02 18:35:44');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (45, 'Spriggin', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 922, 314, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', false, '2014-10-24 00:08:18', '2009-01-18 14:33:49');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (46, 'Keyson', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 19, 617, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', true, '2009-01-01 14:04:39', '2011-02-14 05:18:44');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (47, 'Merrell', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 507, 678, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', false, '2019-08-17 15:37:37', '2022-07-28 12:00:30');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (48, 'Gierok', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 31, 270, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', true, '2018-07-04 16:02:28', '2016-08-13 06:25:52');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (49, 'Stailey', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 731, 171, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', true, '2015-03-28 02:51:23', '2000-10-18 22:48:57');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (50, 'Grollmann', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 943, 821, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', true, '2004-03-25 21:04:44', '2011-01-04 20:55:01');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (51, 'Chapling', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 220, 333, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', false, '2008-01-23 12:42:09', '2017-04-30 10:41:58');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (52, 'De Marchi', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 658, 233, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', true, '2003-08-21 01:42:23', '2021-05-22 13:34:16');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (53, 'Adamiec', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 226, 561, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', false, '2011-02-20 15:02:44', '2013-03-12 16:36:09');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (54, 'Lambswood', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 498, 719, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', true, '2002-05-19 09:43:15', '2004-06-11 09:37:35');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (55, 'Van den Velde', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 811, 861, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', true, '2017-02-19 10:49:46', '2003-11-23 11:20:07');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (56, 'McTrustram', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 331, 724, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', true, '2018-10-12 16:42:21', '2005-05-19 06:32:50');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (57, 'Chese', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 968, 396, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', false, '2018-12-29 02:21:50', '2021-03-10 22:21:08');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (58, 'Kluge', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 600, 139, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', false, '2021-03-20 11:59:32', '2014-05-08 00:21:24');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (59, 'Tuxsell', 'Fusce consequat. Nulla nisl. Nunc nisl.', 392, 821, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', false, '2019-06-19 14:11:01', '2021-04-13 06:44:49');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (60, 'Haversum', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 309, 662, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', false, '2020-11-22 22:09:16', '2016-10-31 17:31:45');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (61, 'Bonnett', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 101, 274, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', true, '2021-10-24 01:20:05', '2016-11-28 02:02:04');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (62, 'Halle', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 336, 911, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', false, '2003-05-15 00:19:04', '2016-04-24 19:43:12');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (63, 'Freak', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 278, 736, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', false, '2003-07-13 12:55:09', '2015-12-06 13:58:44');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (64, 'Okenden', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 510, 286, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', false, '2022-01-05 12:58:02', '2003-04-13 17:25:30');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (65, 'Brogi', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 569, 107, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', true, '2013-03-16 15:21:15', '2002-02-26 19:06:20');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (66, 'Bowery', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 91, 297, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', true, '2016-07-07 10:38:14', '2014-10-21 03:05:27');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (67, 'Sabathe', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 558, 637, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', true, '2016-11-14 23:10:49', '2013-08-20 15:48:28');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (68, 'Fend', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 886, 3, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', true, '2018-12-27 09:00:57', '2021-11-11 00:20:42');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (69, 'Hofton', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 27, 488, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', false, '2021-05-13 03:10:57', '2018-10-25 16:03:59');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (70, 'Tierney', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 777, 960, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', true, '2011-04-17 17:00:23', '2014-01-29 01:51:21');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (71, 'Kindon', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 693, 139, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', false, '2003-01-25 14:54:38', '2007-01-12 00:40:51');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (72, 'Horley', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 670, 447, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', false, '2014-03-22 00:04:47', '2021-09-17 05:14:44');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (73, 'Vannoort', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 341, 831, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', true, '2009-02-12 17:00:03', '2006-09-26 15:53:44');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (74, 'Danelut', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 75, 7, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', true, '2007-09-29 09:33:08', '2021-04-03 16:20:49');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (75, 'Cromly', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 89, 950, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', true, '2009-01-21 21:12:14', '2008-12-20 13:06:46');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (76, 'Colliard', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 137, 949, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', true, '2020-05-10 11:59:41', '2018-07-03 14:33:35');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (77, 'Borton', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 373, 897, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', false, '2013-08-18 17:23:21', '2004-01-26 10:13:28');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (78, 'Murch', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 536, 521, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', false, '2002-12-03 07:16:48', '2000-07-13 16:34:18');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (79, 'Ledrane', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 787, 302, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', true, '2004-01-13 05:49:44', '2018-07-21 02:14:23');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (80, 'Glennon', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 607, 539, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', false, '2021-04-24 04:28:57', '2013-05-07 21:49:28');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (81, 'Lindenstrauss', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 450, 742, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', true, '2014-10-27 14:17:21', '2004-05-10 21:09:07');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (82, 'Jamison', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 286, 274, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', true, '2005-09-09 04:02:50', '2017-05-07 18:26:07');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (83, 'Corbert', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 147, 658, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', false, '2005-07-12 20:08:29', '2022-11-10 06:40:27');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (84, 'Doogan', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 412, 433, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', true, '2011-08-27 14:25:30', '2011-01-24 04:52:18');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (85, 'Brisley', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 345, 195, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', false, '2018-10-18 04:53:52', '2011-10-01 01:49:23');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (86, 'Sunshine', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 258, 230, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', false, '2022-03-29 07:44:01', '2001-04-05 01:59:28');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (87, 'Chappelow', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 356, 378, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', false, '2015-03-06 01:51:36', '2002-08-10 23:32:03');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (88, 'Geraldo', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 953, 374, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', true, '2009-03-04 12:34:45', '2001-10-11 13:31:44');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (89, 'Baumann', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 179, 66, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', true, '2002-02-28 05:24:22', '2016-01-05 23:56:36');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (90, 'Drepp', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 782, 970, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', false, '2010-11-15 06:20:08', '2004-08-11 23:32:17');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (91, 'Rummer', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 498, 718, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', true, '2003-11-16 23:06:50', '2020-03-26 03:49:17');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (92, 'Ledamun', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 704, 250, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', false, '2015-01-17 15:48:51', '2013-09-11 19:11:04');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (93, 'Arlidge', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 384, 896, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', false, '2015-12-29 11:54:27', '2022-02-08 17:05:05');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (94, 'Dumphry', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 691, 979, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', true, '2011-10-19 18:00:56', '2020-04-25 15:43:06');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (95, 'Troke', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 622, 487, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', false, '2009-06-21 07:24:08', '2020-02-18 18:12:10');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (96, 'Moresby', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 461, 244, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', true, '2007-02-11 01:07:46', '2022-05-20 02:27:57');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (97, 'Scaysbrook', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 380, 183, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', false, '2009-07-08 16:34:56', '2003-02-09 09:07:20');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (98, 'Mellonby', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 270, 85, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', false, '2009-04-02 12:09:15', '2004-09-10 00:17:06');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (99, 'Stanlike', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 377, 394, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', false, '2001-02-21 21:20:57', '2004-02-06 08:27:16');
insert into recipe (id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (100, 'Mallon', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 752, 792, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', false, '2022-11-04 13:18:56', '2004-09-26 12:28:55');

select * from recipe;
select * from user;

-- 테스트 쿼리
INSERT INTO recipe (name, description, num_of_servings, cook_time, directions)
VALUES ('Recipe Name', 'Recipe Description', 4, 45, 'Recipe Directions');

SELECT * FROM recipe LIMIT 0, 25;